### ISSUE TITLE
sql exception / use of illegal characters

### ISSUE THREAD

**Issue by dweSheppard** [masagameplay/MaSuiteHomes#11]
I get these exception when using illegal characters like

- /sethome '
- /delhome '

https://pastebin.com/eRJx2G0v

**Comment by NeverminedDE** [comment]
@masagameplay You can work around the error with regex.

For example:  [0-9,a-z,A-Z-_]

code example (not testet): 

Pattern namePattern = Pattern.compile("^[0-9,a-z,A-Z-_]+$");
Matcher nameMatcher = namePattern.matcher(homeName);
if (nameMatcher.find()) {
    //legal name
}

or shorter:

boolean legal = homeName.matches("^[0-9,a-z,A-Z-_]+$");

**Comment by masagameplay** [comment]
Fixed in the 2.0.1 on SpigotMC
