### ISSUE TITLE
Updating home's location isn't possible if limit is reached

### ISSUE THREAD

**Issue by Vimppura69** [masagameplay/MaSuiteHomes#19]
Previously set home point cannot be updated to a new location without deleting it first IF player's home limit is reached. It cancels the updation event with error "&cYou have reached home limit", even tho home can be set if it has been deleted first. No errors can be found from Console. This error slows people down alot and it would be amazing if it could be fixed in the near future.

**Comment by LillithaCT** [comment]
Our players are reporting the same problem.

**Comment by masagameplay** [comment]
Fixed in the latest devbuilds.
